name: medical_image_proc
channels:
  - conda-forge
  
dependencies:
  - python=3.10
  - dcm2niix=1.0.20240202
  - ipywidgets=8.1.3
  - jupyter=1.0.0
  - jupyterlab=3.6.1
  - matplotlib=3.3.3
  - nibabel=5.2.1
  - notebook=6.4.10
  - numpy=1.22.3
  - pandas=2.2.2
  - pydicom=2.4.4
  - scikit-image=0.24.0
  - simpleitk=2.3.1
  - zenodo_get=1.6.1
